### ISSUE TITLE
Client interface

### ISSUE THREAD

**Issue by rikonor** [datamountaineer/schema-registry#6]
Hi,

We're using this project and thought it might benefit from `Client` being an interface rather then a struct.

This allows one to mock the `Client`, among other possibilities.

Currently, we're using a fork with this [change](https://github.com/securityscorecard/go-schema-registry-client/pull/1/files), but I figured I might as well suggest it here in case there's interest.

If there is, please let me know and I can submit a PR.

**Comment by andrewstevenson** [comment]
Yes, can you submit a PR?
________________________________

**Comment by rollulus** [comment]
Thanks a lot, @rikonor, good job!
